
spring:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8081
  context-path: /mgmt

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    uk.gov.cshr: ${CSHR_LOGGING_LEVEL:INFO}

security:
  oauth2:
    resource:
      prefer-token-info: true
      jwt:
        key-value: ${jwt_key:key}
    client:
      client-id: ${CLIENT_ID:management}
      client-secret: ${CLIENT_SECRET:test}
      access-token-uri: ${identity.url}${identity.oauthTokenEndpoint}
      user-authorization-uri: ${identity.url}${identity.oauthAuthorizationEndpoint}
      reset-uri: ${identity.url}/reset
      reactivation-url: "${identity.url}/account/reactivate/%s"

identity:
  url: ${OAUTH_URL:http://localhost:8080}
  signoutUrl: ${identity.url}/logout
  idmLoginUrl: ${IDM_URL:http://localhost:8081}/mgmt/login
  oauthLogoutEndpoint: ${OAUTH_LOGOUT_ENDPOINT:/logout}
  oauthTokenEndpoint: ${OAUTH_TOKEN_ENDPOINT:/oauth2/token}
  oauthAuthorizationEndpoint: ${OAUTH_AUTHORIZATION_ENDPOINT:/oauth2/authorize}

learnerRecord:
  serviceUrl: ${LEARNER_RECORD_URL:http://localhost:9000}
  deleteUrl: "${learnerRecord.serviceUrl}/learner/%s"

csrs:
  serviceUrl: ${REGISTRY_SERVICE_URL:http://localhost:9002}
  deleteUrl: "${csrs.serviceUrl}/civilServants/%s/delete"
  getCivilServant: "${csrs.serviceUrl}/civilServants/resource/%s"
  getAgencyToken: "${csrs.serviceUrl}/agencyTokens"

cslService:
  serviceUrl: ${CSL_SERVICE_URL:http:localhost:9003}
  getRequiredLearningUrl: "${cslService.serviceUrl}/api/learning/required/detailed"

notifications:
  service: ${NOTIFICATION_SERVICE_URL:http://localhost:9006}
  email: "${notifications.service}/notifications/email"

reporting:
  serviceUrl: ${REPORTING_SERVICE_URL:http://localhost:9004}
  removeUserDataUrl: "${reporting.serviceUrl}/course-completions/remove-user-details"
  removeUserDataFromReportUrl: "${reporting.serviceUrl}/api/report/remove-user-details"

accountPeriodsInMonths:
  deactivation: 13
  notification: 24
  deletion: 26

dataRetentionJob:
  cronSchedule: ${DATA_RETENTION_JOB_CRON_SCHEDULE:0 0 5 * * *}
  enabled: ${DATA_RETENTION_JOB_ENABLED:true}

govNotify:
  template:
    accountSuspension: ${GOV_NOTIFY_ACCOUNT_SUSPENSION_TEMPLATE_ID:de47fe22-96fc-448f-a3f0-d105e9f0e0e6}
    accountDeletion: ${GOV_NOTIFY_ACCOUNT_DELETION_TEMPLATE_ID:5830199c-a524-458c-a630-c1b64734cf18}
    accountDeleted: ${GOV_NOTIFY_ACCOUNT_DELETED_TEMPLATE_ID:f8aa74fb-eaaf-4e4e-a6fc-f6a9a703b686}
    reactivationTemplateId: ${GOV_NOTIFY_REACTIVATION_TEMPLATE_ID:abfb2e5f-3905-4817-b041-c53afd1eb3e5}

---

database:
  host: ${DATABASE_HOST:jdbc:mysql://localhost:3306}
  name: ${DATABASE_NAME:identity}
  use-ssl: ${DATABASE_USESSL:false}

spring:
  profiles: test, production
  thymeleaf:
    cache: true
  datasource:
    url: ${DATASOURCE_URL:${database.host}/${database.name}?useSSL=${database.use-ssl}&requireSSL=false}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:my-secret-pw}
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
