spring:
  thymeleaf:
    cache: ${THYMELEAF_CACHE:true}
    prefix: file:src/main/resources/templates/
  datasource:
    url: ${DATASOURCE_URL:${database.host}/${database.name}?useSSL=${database.use-ssl}&requireSSL=false}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:my-secret-pw}
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
        ddl-auto: none

database:
  host: ${DATABASE_HOST:jdbc:mysql://localhost:3306}
  name: ${DATABASE_NAME:identity}
  use-ssl: ${DATABASE_USESSL:false}

server:
  port: 8081
  context-path: /mgmt

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    uk.gov.cshr: ${CSHR_LOGGING_LEVEL:INFO}

security:
  oauth2:
    resource:
      prefer-token-info: true
      jwt:
        key-value: ${JWT_KEY:key}
    client:
      client-id: ${CLIENT_ID:management}
      client-secret: ${CLIENT_SECRET:test}
      access-token-uri: ${identity.url}${identity.oauthTokenEndpoint}
      user-authorization-uri: ${identity.url}${identity.oauthAuthorizationEndpoint}
      reset-uri: ${identity.url}/reset
      reactivation-url: "${identity.url}/account/reactivate/%s"

identity:
  url: ${OAUTH_URL:http://localhost:8080}
  signoutUrl: ${identity.url}/logout
  idmLoginUrl: ${IDM_URL:http://localhost:8081}/mgmt/login
  oauthLogoutEndpoint: ${OAUTH_LOGOUT_ENDPOINT:/logout}
  oauthTokenEndpoint: ${OAUTH_TOKEN_ENDPOINT:/oauth2/token}
  oauthAuthorizationEndpoint: ${OAUTH_AUTHORIZATION_ENDPOINT:/oauth2/authorize}

learnerRecord:
  serviceUrl: ${LEARNER_RECORD_URL:http://localhost:9000}
  deleteUrl: "${learnerRecord.serviceUrl}/learner/%s"

csrs:
  serviceUrl: ${REGISTRY_SERVICE_URL:http://localhost:9002}
  deleteUrl: "${csrs.serviceUrl}/civilServants/%s/delete"
  getCivilServant: "${csrs.serviceUrl}/civilServants/resource/%s"
  getAgencyToken: "${csrs.serviceUrl}/agencyTokens"
  updateOtherOrgUnitsUrl: "${csrs.serviceUrl}/civilServants/%s"

cslService:
  serviceUrl: ${CSL_SERVICE_URL:http://localhost:9003}
  getRequiredLearningUrl: "${cslService.serviceUrl}/api/learning/required/detailed"
  getFormattedOrganisationNames: "${cslService.serviceUrl}/api/organisations/formatted_list"
  getUserLearningUrl: "${cslService.serviceUrl}/api/learning"
  getDetailedLearningUrl: "${cslService.serviceUrl}/api/learning/detailed"

notifications:
  service: ${NOTIFICATION_SERVICE_URL:http://localhost:9006}
  email: "${notifications.service}/notifications/emails"
  bulkEmail: "${notifications.email}/bulk/send"
  bulkBatchSize: ${NOTIFICATION_SERVICE_BULK_BATCH_SIZE:20}

reporting:
  serviceUrl: ${REPORTING_SERVICE_URL:http://localhost:9004}
  registeredLearners:
    url: "${reporting.serviceUrl}/registered-learners"
    deactivateUrl: "${reporting.registeredLearners.url}/deactivate"
    deactivationBatchSize: ${REPORTING_DEACTIVATION_BATCH_SIZE:50}
  api:
    url: "${reporting.serviceUrl}/api/report"
    removeUserDataFromReportUrl: "${reporting.api.url}/remove-user-details"

accountPeriodsInMonths:
  deactivation: 13
  notification: 24
  deletion: 26

dataRetentionJob:
  cronSchedule: ${DATA_RETENTION_JOB_CRON_SCHEDULE:0 0 5 * * *}
  enabled: ${DATA_RETENTION_JOB_ENABLED:true}
  deactivationBatchSize: ${DR_DEACTIVATION_BATCH_SIZE:1000}

govNotify:
  templateName:
    accountSuspension: ${ACCOUNT_SUSPENSION_TEMPLATE_NAME:ACCOUNT_DEACTIVATED}
    accountDeletion: ${ACCOUNT_DELETION_TEMPLATE_NAME:ACCOUNT_DELETION_WARNING}
    accountDeleted: ${ACCOUNT_DELETED_TEMPLATE_NAME:ACCOUNT_DELETED}
    reactivation: ${REACTIVATION_TEMPLATE_NAME:ACCOUNT_REACTIVATED}

pagination:
  pageSize: ${PAGINATION_PAGE_SIZE:20}
