
spring:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8081
  context-path: /mgmt

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:management}
      client-secret: ${CLIENT_SECRET:test}
      access-token-uri: ${OAUTH_URL:http://localhost:8080}/oauth/token
      user-authorization-uri: ${OAUTH_URL:http://localhost:8080}/oauth/authorize
    resource:
      user-info-uri: ${OAUTH_URL:http://localhost:8080}/oauth/resolve

invite:
  url: ${INVITE_SIGNUP_URL:http://localhost:8080/signup/%s}
  validityInSeconds: ${INVITE_VALIDITY:259200}

learnerRecord:
  serviceUrl: ${LEARNER_RECORD_URL:http://localhost:9000}
  deleteUrl: "${learnerRecord.serviceUrl}/learner/%s"

csrs:
  serviceUrl: ${REGISTRY_SERVICE_URL:http://localhost:9002}
  deleteUrl: "${csrs.serviceUrl}/civilServants/%s"

notifications:
  service: ${NOTIFICATION_SERVICE_URL:http://localhost:9005}
  email: "${notifications.service}/notifications/email/"

accountPeriodsInMonths:
  deactivation: 13
  notification: 25
  deletion: 26

govNotify:
  template:
    invite: ${GOV_NOTIFY_INVITE_TEMPLATE_ID:7ef048a3-5c82-40fd-be4c-a238ce328fea}
    accountSuspension: ${GOV_NOTIFY_ACCOUNT_SUSPENSION_TEMPLATE_ID:de47fe22-96fc-448f-a3f0-d105e9f0e0e6}
    accountDeletion: ${GOV_NOTIFY_ACCOUNT_DELETION_TEMPLATE_ID:5830199c-a524-458c-a630-c1b64734cf18}

---
spring:
  profiles: production
  thymeleaf:
    cache: true
  datasource:
    url: ${DATASOURCE:jdbc:mysql://localhost:3306/oauth2?user=root&password=password&useSSL=false}
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
